version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social_db
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
